import Head from 'next/head'
import Image from 'next/image'
import React, {useEffect} from 'react'
import { useSelector, useDispatch } from 'react-redux';
import Products from '../components/Products';
import {setProducts, selectList} from '../components/Products/productSlice'
import { fetchDataAsync } from '../utils';

const Home = props => {

  const dispatch = useDispatch();
  const listData = useSelector(selectList);
  
  const hasListData = () => (listData && listData.length>0) ? true : false
  
  useEffect(()=>{
    /**
     * URL at 'https://cdn.shopify.com/s/files/1/0455/2176/4502/files/products.json'
     * has a trailing ',' issue hence cannot be parsed; using local file instead 
     */
    //
    if(!hasListData()){
      fetchDataAsync('./products.json').then(data => {
        //console.log('fetchDataAsync loaded ', data);
        dispatch(setProducts(data));
      })
    }
    
  }, []);

  return (
    <div className="">
      <Head>
        <title>ShopTrade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Layout */}
      <main className="layout-grid">
        {hasListData() 
          ? <div className="content"><Products /></div> 
          : <div className="image-loader">
              <Image src='/loading.gif' width='50px' height='50px' alt="loading" />
            </div>
        } 
      </main>
    </div>
  )
}


/* 
//.. ToDo: Server side implementation
export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/getproducts')
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { 
      lists: data,
      tags: unique(data.map(item => item.tag))
    },
  }
} */

export default Home